#!/usr/bin/env bash

set -euo pipefail

case "${JANITOR_TASK:-}" in
	stop-sandboxes)
		buildkite-agent pipeline upload .buildkite/stop-sandboxes.yml
		;;
	*)
		echo "Don't know what to do!" 1>&2
		exit 1
esac
